version: '3'
services:
  server:
    build: .
    depends_on:
      - database
    links:
      - database:database
    ports:
      - "8080:8080"
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: root
      POSTGRES_DB: qwerty